package dcc025.trabalho.model;

public enum SubTipoProduto {
    N_A, SAPATO, CALCA, BLUSA, CONJUNTO, ACESSORIOS,  
    ASSENTO, MESA, ESTANTE, QUADRO, LUMINARIA, ARMARIO, CAMA,
    CANETA, LAPIS, BORRACHA, PAPEL, CLIPES,
    GELADEIRA, FOGAO, COMPUTADOR, TV, MAQUINA_DE_LAVAR

}
